packages:
  - 'apps/**/*'
  - 'packages/**/*'

catalog:
  '@pandacss/dev': 1.4.1

catalogs:
  react19:
    react: ^19.3.0-canary-a757cb76-20251002
    react-dom: ^19.3.0-canary-a757cb76-20251002
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0

  typescript5:
    typescript: 5.8.3
