import Head from 'next/head';
import { css } from '@design-system/ui-lib/css';
import { Button } from '@design-system/ui';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={css({
          color: 'red',
        })}
      >
        ㅁㅁ
        <Button>count</Button>
      </div>
    </>
  );
}
