-- Create a table to log every view event for history tracking
create table if not exists public.post_view_logs (
  id bigint generated by default as identity primary key,
  slug text not null,
  viewed_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.post_view_logs enable row level security;

-- Policies
-- We might want to allow admins to read this, but for now we keep it internal or viewable by service role.
-- No public read access to logs by default to protect granularity/privacy if IP were involved (though it's not here).

-- Update the function to log the view
create or replace function public.increment_view_count(slug_input text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- 1. Upsert into post_views (Stats aggregation)
  insert into public.post_views (slug, view_count, updated_at)
  values (slug_input, 1, now())
  on conflict (slug)
  do update set
    view_count = post_views.view_count + 1,
    updated_at = now();

  -- 2. Log the individual view event (History tracking)
  insert into public.post_view_logs (slug, viewed_at)
  values (slug_input, now());
end;
$$;
